# Default values for vote-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mcr.microsoft.com/azuredocs/azure-vote-front
  tag: v1

redis:
  repository: mcr.microsoft.com/oss/bitnami/redis
  tag: "6.0.8"