dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://raw.githubusercontent.com/msazurestackworkloads/helm-charts/master/repo/
    condition: mariadb.enabled
    tags:
      - wordpress-database
